version: "3.3"

services:
  cs16-mix:
    image: tsaki/hlds-cs16
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27015:27015/udp"
      - "27015:27015"
    environment:
      - "LOGIN=anonymous"
      - "ADMIN_STEAM_ID=STEAM_0:1:17570273"