version: "3.3"

services:
  hlds-cs16:
    image: tsaki/hlds-cs16
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27015:27015/udp"
      - "27015:27015"
    environment:
      - "LOGIN=anonymous"
      - "ADMIN_STEAM_ID=STEAM_0:1:12345678"
      - "SV_LAN=0"
      - "MAP=de_dust2"
      - "MAX_PLAYERS=32"
      - "OPTIONS=-insecure"
    volumes:
      - "hlds-cs16:/opt/hlds"
