version: "3.3"

services:
  hlds-cs16:
    container_name: hlds-cs16-amxmodx
    image: tsaki/hlds-cs16-amxmodx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27015:27015/udp"
      - "27015:27015"
    environment:
      - "LOGIN=anonymous"
      - "LAUNCH_OPTIONS=+sv_lan 0 +map de_dust2 -maxplayers 32"
    volumes:
      - "hlds-cs16:/opt/hlds"

volumes:
  hlds-cs16:
